[telegram]
token   = "7882400771:AAHlccDgk1Se8ryHWG6XZTMvr2eqoR7f6R8"
chat_id = 6436047826

[smtp]
server       = "smtp.gmail.com"
port         = 465
username     = "levelofspeed@gmail.com"
password     = "ljpnteoquqdziemj"
sender_email = "levelofspeed@gmail.com"
